# Generated by Django 2.2.7 on 2019-12-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
