# Generated by Django 2.2.7 on 2019-12-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='postpicture',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='blog.Post'),
        ),
    ]
