# Generated by Django 2.2.7 on 2019-12-24 12:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='DEFAULT VALUE', upload_to='media'),
        ),
    ]
