# Generated by Django 2.2.7 on 2019-12-24 14:16

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_image_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='DEFAULT VALUE', upload_to='thumbnail'),
        ),
        migrations.AlterField(
            model_name='postpicture',
            name='picture',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
