# Generated by Django 2.2.3 on 2019-12-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191224_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpicture',
            name='postid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
