# Generated by Django 2.2.3 on 2019-12-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191225_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpicture',
            old_name='postid',
            new_name='post',
        ),
    ]
